-- Canonical answer keys generated from src/lib/quranExercises.ts and quranSurahs.ts.
-- Update together with the question bank; client scores are verified server-side.
BEGIN;
INSERT INTO public.quran_practice_keys(practice_type,question_id,answer,surah_id,ayah,topic) VALUES
('completion','completion-1-1-بِسْمِ','اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',1,1,'Fâtiha'),
('completion','completion-1-1-بِسْمِ اللَّهِ','الرَّحْمَٰنِ الرَّحِيمِ',1,1,'Fâtiha'),
('completion','completion-1-1-بِسْمِ اللَّهِ الرَّحْمَٰنِ','الرَّحِيمِ',1,1,'Fâtiha'),
('completion','completion-1-2-الْحَمْدُ','لِلَّهِ رَبِّ الْعَالَمِينَ',1,2,'Fâtiha'),
('completion','completion-1-2-الْحَمْدُ لِلَّهِ','رَبِّ الْعَالَمِينَ',1,2,'Fâtiha'),
('completion','completion-1-2-الْحَمْدُ لِلَّهِ رَبِّ','الْعَالَمِينَ',1,2,'Fâtiha'),
('completion','completion-1-3-الرَّحْمَٰنِ','الرَّحِيمِ',1,3,'Fâtiha'),
('completion','completion-1-4-مَالِكِ','يَوْمِ الدِّينِ',1,4,'Fâtiha'),
('completion','completion-1-4-مَالِكِ يَوْمِ','الدِّينِ',1,4,'Fâtiha'),
('completion','completion-1-5-إِيَّاكَ','نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',1,5,'Fâtiha'),
('completion','completion-1-5-إِيَّاكَ نَعْبُدُ','وَإِيَّاكَ نَسْتَعِينُ',1,5,'Fâtiha'),
('completion','completion-1-5-إِيَّاكَ نَعْبُدُ وَإِيَّاكَ','نَسْتَعِينُ',1,5,'Fâtiha'),
('completion','completion-1-6-اهْدِنَا','الصِّرَاطَ الْمُسْتَقِيمَ',1,6,'Fâtiha'),
('completion','completion-1-6-اهْدِنَا الصِّرَاطَ','الْمُسْتَقِيمَ',1,6,'Fâtiha'),
('completion','completion-1-7-صِرَاطَ','الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',1,7,'Fâtiha'),
('completion','completion-1-7-صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ','غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',1,7,'Fâtiha'),
('completion','completion-1-7-صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا','الضَّالِّينَ',1,7,'Fâtiha'),
('completion','completion-112-1-قُلْ','هُوَ اللَّهُ أَحَدٌ',112,1,'İhlâs'),
('completion','completion-112-1-قُلْ هُوَ','اللَّهُ أَحَدٌ',112,1,'İhlâs'),
('completion','completion-112-1-قُلْ هُوَ اللَّهُ','أَحَدٌ',112,1,'İhlâs'),
('completion','completion-112-2-اللَّهُ','الصَّمَدُ',112,2,'İhlâs'),
('completion','completion-112-3-لَمْ','يَلِدْ وَلَمْ يُولَدْ',112,3,'İhlâs'),
('completion','completion-112-3-لَمْ يَلِدْ','وَلَمْ يُولَدْ',112,3,'İhlâs'),
('completion','completion-112-3-لَمْ يَلِدْ وَلَمْ','يُولَدْ',112,3,'İhlâs'),
('completion','completion-112-4-وَلَمْ','يَكُن لَّهُ كُفُوًا أَحَدٌ',112,4,'İhlâs'),
('completion','completion-112-4-وَلَمْ يَكُن','لَّهُ كُفُوًا أَحَدٌ',112,4,'İhlâs'),
('completion','completion-112-4-وَلَمْ يَكُن لَّهُ كُفُوًا','أَحَدٌ',112,4,'İhlâs'),
('completion','completion-113-1-قُلْ','أَعُوذُ بِرَبِّ الْفَلَقِ',113,1,'Felâk'),
('completion','completion-113-1-قُلْ أَعُوذُ','بِرَبِّ الْفَلَقِ',113,1,'Felâk'),
('completion','completion-113-1-قُلْ أَعُوذُ بِرَبِّ','الْفَلَقِ',113,1,'Felâk'),
('completion','completion-113-2-مِن','شَرِّ مَا خَلَقَ',113,2,'Felâk'),
('completion','completion-113-2-مِن شَرِّ','مَا خَلَقَ',113,2,'Felâk'),
('completion','completion-113-2-مِن شَرِّ مَا','خَلَقَ',113,2,'Felâk'),
('completion','completion-113-3-وَمِن','شَرِّ غَاسِقٍ إِذَا وَقَبَ',113,3,'Felâk'),
('completion','completion-113-3-وَمِن شَرِّ','غَاسِقٍ إِذَا وَقَبَ',113,3,'Felâk'),
('completion','completion-113-3-وَمِن شَرِّ غَاسِقٍ إِذَا','وَقَبَ',113,3,'Felâk'),
('completion','completion-113-4-وَمِن','شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ',113,4,'Felâk'),
('completion','completion-113-4-وَمِن شَرِّ','النَّفَّاثَاتِ فِي الْعُقَدِ',113,4,'Felâk'),
('completion','completion-113-4-وَمِن شَرِّ النَّفَّاثَاتِ فِي','الْعُقَدِ',113,4,'Felâk'),
('completion','completion-113-5-وَمِن','شَرِّ حَاسِدٍ إِذَا حَسَدَ',113,5,'Felâk'),
('completion','completion-113-5-وَمِن شَرِّ','حَاسِدٍ إِذَا حَسَدَ',113,5,'Felâk'),
('completion','completion-113-5-وَمِن شَرِّ حَاسِدٍ إِذَا','حَسَدَ',113,5,'Felâk'),
('completion','completion-114-1-قُلْ','أَعُوذُ بِرَبِّ النَّاسِ',114,1,'Nâs'),
('completion','completion-114-1-قُلْ أَعُوذُ','بِرَبِّ النَّاسِ',114,1,'Nâs'),
('completion','completion-114-1-قُلْ أَعُوذُ بِرَبِّ','النَّاسِ',114,1,'Nâs'),
('completion','completion-114-2-مَلِكِ','النَّاسِ',114,2,'Nâs'),
('completion','completion-114-3-إِلَٰهِ','النَّاسِ',114,3,'Nâs'),
('completion','completion-114-4-مِن','شَرِّ الْوَسْوَاسِ الْخَنَّاسِ',114,4,'Nâs'),
('completion','completion-114-4-مِن شَرِّ','الْوَسْوَاسِ الْخَنَّاسِ',114,4,'Nâs'),
('completion','completion-114-4-مِن شَرِّ الْوَسْوَاسِ','الْخَنَّاسِ',114,4,'Nâs'),
('completion','completion-114-5-الَّذِي','يُوَسْوِسُ فِي صُدُورِ النَّاسِ',114,5,'Nâs'),
('completion','completion-114-5-الَّذِي يُوَسْوِسُ','فِي صُدُورِ النَّاسِ',114,5,'Nâs'),
('completion','completion-114-5-الَّذِي يُوَسْوِسُ فِي صُدُورِ','النَّاسِ',114,5,'Nâs'),
('completion','completion-114-6-مِنَ','الْجِنَّةِ وَالنَّاسِ',114,6,'Nâs'),
('completion','completion-114-6-مِنَ الْجِنَّةِ','وَالنَّاسِ',114,6,'Nâs'),
('completion','completion-108-1-إِنَّا','أَعْطَيْنَاكَ الْكَوْثَرَ',108,1,'Kevser'),
('completion','completion-108-1-إِنَّا أَعْطَيْنَاكَ','الْكَوْثَرَ',108,1,'Kevser'),
('completion','completion-108-2-فَصَلِّ','لِرَبِّكَ وَانْحَرْ',108,2,'Kevser'),
('completion','completion-108-2-فَصَلِّ لِرَبِّكَ','وَانْحَرْ',108,2,'Kevser'),
('completion','completion-108-3-إِنَّ','شَانِئَكَ هُوَ الْأَبْتَرُ',108,3,'Kevser'),
('completion','completion-108-3-إِنَّ شَانِئَكَ','هُوَ الْأَبْتَرُ',108,3,'Kevser'),
('completion','completion-108-3-إِنَّ شَانِئَكَ هُوَ','الْأَبْتَرُ',108,3,'Kevser'),
('completion','completion-103-2-إِنَّ','الْإِنسَانَ لَفِي خُسْرٍ',103,2,'Asr'),
('completion','completion-103-2-إِنَّ الْإِنسَانَ','لَفِي خُسْرٍ',103,2,'Asr'),
('completion','completion-103-2-إِنَّ الْإِنسَانَ لَفِي','خُسْرٍ',103,2,'Asr'),
('completion','completion-103-3-إِلَّا','الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',103,3,'Asr'),
('completion','completion-103-3-إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا','الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',103,3,'Asr'),
('completion','completion-103-3-إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا','بِالصَّبْرِ',103,3,'Asr'),
('completion','completion-109-1-قُلْ','يَا أَيُّهَا الْكَافِرُونَ',109,1,'Kâfirûn'),
('completion','completion-109-1-قُلْ يَا','أَيُّهَا الْكَافِرُونَ',109,1,'Kâfirûn'),
('completion','completion-109-1-قُلْ يَا أَيُّهَا','الْكَافِرُونَ',109,1,'Kâfirûn'),
('completion','completion-109-2-لَا','أَعْبُدُ مَا تَعْبُدُونَ',109,2,'Kâfirûn'),
('completion','completion-109-2-لَا أَعْبُدُ','مَا تَعْبُدُونَ',109,2,'Kâfirûn'),
('completion','completion-109-2-لَا أَعْبُدُ مَا','تَعْبُدُونَ',109,2,'Kâfirûn'),
('completion','completion-109-3-وَلَا','أَنتُمْ عَابِدُونَ مَا أَعْبُدُ',109,3,'Kâfirûn'),
('completion','completion-109-3-وَلَا أَنتُمْ','عَابِدُونَ مَا أَعْبُدُ',109,3,'Kâfirûn'),
('completion','completion-109-3-وَلَا أَنتُمْ عَابِدُونَ مَا','أَعْبُدُ',109,3,'Kâfirûn'),
('completion','completion-109-4-وَلَا','أَنَا عَابِدٌ مَّا عَبَدتُّمْ',109,4,'Kâfirûn'),
('completion','completion-109-4-وَلَا أَنَا','عَابِدٌ مَّا عَبَدتُّمْ',109,4,'Kâfirûn'),
('completion','completion-109-4-وَلَا أَنَا عَابِدٌ مَّا','عَبَدتُّمْ',109,4,'Kâfirûn'),
('completion','completion-109-5-وَلَا','أَنتُمْ عَابِدُونَ مَا أَعْبُدُ',109,5,'Kâfirûn'),
('completion','completion-109-5-وَلَا أَنتُمْ','عَابِدُونَ مَا أَعْبُدُ',109,5,'Kâfirûn'),
('completion','completion-109-5-وَلَا أَنتُمْ عَابِدُونَ مَا','أَعْبُدُ',109,5,'Kâfirûn'),
('completion','completion-109-6-لَكُمْ','دِينُكُمْ وَلِيَ دِينِ',109,6,'Kâfirûn'),
('completion','completion-109-6-لَكُمْ دِينُكُمْ','وَلِيَ دِينِ',109,6,'Kâfirûn'),
('completion','completion-109-6-لَكُمْ دِينُكُمْ وَلِيَ','دِينِ',109,6,'Kâfirûn'),
('tajweed','tajweed-نْ رَ','İdğâm',0,0,'İdğâm'),
('tajweed','tajweed-نْ لَ','İdğâm',0,0,'İdğâm'),
('tajweed','tajweed-نْ يَ','İdğâm',0,0,'İdğâm'),
('tajweed','tajweed-نْ وَ','İdğâm',0,0,'İdğâm'),
('tajweed','tajweed-نْ مَ','İdğâm',0,0,'İdğâm'),
('tajweed','tajweed-نْ نَ','İdğâm',0,0,'İdğâm'),
('tajweed','tajweed-نْ ءَ','İzhâr',0,0,'İzhâr'),
('tajweed','tajweed-نْ هَ','İzhâr',0,0,'İzhâr'),
('tajweed','tajweed-نْ عَ','İzhâr',0,0,'İzhâr'),
('tajweed','tajweed-نْ حَ','İzhâr',0,0,'İzhâr'),
('tajweed','tajweed-نْ غَ','İzhâr',0,0,'İzhâr'),
('tajweed','tajweed-نْ خَ','İzhâr',0,0,'İzhâr'),
('tajweed','tajweed-نْ تَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ ثَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ جَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ دَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ ذَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ زَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ سَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ شَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ صَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ ضَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ طَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ ظَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ فَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ قَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ كَ','İhfâ',0,0,'İhfâ'),
('tajweed','tajweed-نْ بَ','İklâb',0,0,'İklâb'),
('tajweed','tajweed-قْ','Kalkale',0,0,'Kalkale'),
('tajweed','tajweed-طْ','Kalkale',0,0,'Kalkale'),
('tajweed','tajweed-بْ','Kalkale',0,0,'Kalkale'),
('tajweed','tajweed-جْ','Kalkale',0,0,'Kalkale'),
('tajweed','tajweed-دْ','Kalkale',0,0,'Kalkale'),
('tajweed','tajweed-نَّ','Ğunne',0,0,'Ğunne'),
('tajweed','tajweed-مَّ','Ğunne',0,0,'Ğunne'),
('tajweed','tajweed-بَا','Med',0,0,'Med'),
('tajweed','tajweed-بِي','Med',0,0,'Med'),
('tajweed','tajweed-بُو','Med',0,0,'Med'),
('meaning','meaning-1-2','Övgü, âlemlerin Rabbi Allah’a aittir.',1,2,'Fâtiha'),
('meaning','meaning-1-3','Allah’ın engin merhameti vurgulanır.',1,3,'Fâtiha'),
('meaning','meaning-1-4','Hesap gününün egemenliği Allah’a aittir.',1,4,'Fâtiha'),
('meaning','meaning-1-5','Yalnız Allah’a kulluk edilir ve O’ndan yardım istenir.',1,5,'Fâtiha'),
('meaning','meaning-1-6','Dosdoğru yola iletilme duası yapılır.',1,6,'Fâtiha'),
('meaning','meaning-112-1','Allah’ın bir ve tek olduğu bildirilir.',112,1,'İhlâs'),
('meaning','meaning-112-2','Her şey Allah’a muhtaçtır; O ise hiçbir şeye muhtaç değildir.',112,2,'İhlâs'),
('meaning','meaning-112-3','Allah’ın doğurmadığı ve doğurulmadığı bildirilir.',112,3,'İhlâs'),
('meaning','meaning-112-4','Hiçbir varlığın Allah’a denk olmadığı bildirilir.',112,4,'İhlâs'),
('meaning','meaning-108-2','Rab için namaz kılma ve kurban kesme emredilir.',108,2,'Kevser'),
('meaning','meaning-109-6','İnanç konusundaki ayrılık açıkça ifade edilir.',109,6,'Kâfirûn'),
('meaning','meaning-113-1','Sabahın Rabbine sığınma öğretilir.',113,1,'Felâk'),
('letters','letters-ا','Elif',0,0,'Elif'),
('letters','letters-ب','Bâ',0,0,'Bâ'),
('letters','letters-ت','Tâ',0,0,'Tâ'),
('letters','letters-ث','Sâ',0,0,'Sâ'),
('letters','letters-ج','Cîm',0,0,'Cîm'),
('letters','letters-ح','Hâ (ح)',0,0,'Hâ (ح)'),
('letters','letters-خ','Hı',0,0,'Hı'),
('letters','letters-د','Dâl',0,0,'Dâl'),
('letters','letters-ذ','Zâl',0,0,'Zâl'),
('letters','letters-ر','Râ',0,0,'Râ'),
('letters','letters-ز','Zây',0,0,'Zây'),
('letters','letters-س','Sîn',0,0,'Sîn'),
('letters','letters-ش','Şîn',0,0,'Şîn'),
('letters','letters-ص','Sâd',0,0,'Sâd'),
('letters','letters-ض','Dâd',0,0,'Dâd'),
('letters','letters-ط','Tı',0,0,'Tı'),
('letters','letters-ظ','Zı',0,0,'Zı'),
('letters','letters-ع','Ayn',0,0,'Ayn'),
('letters','letters-غ','Gayn',0,0,'Gayn'),
('letters','letters-ف','Fâ',0,0,'Fâ'),
('letters','letters-ق','Kâf (ق)',0,0,'Kâf (ق)'),
('letters','letters-ك','Kef (ك)',0,0,'Kef (ك)'),
('letters','letters-ل','Lâm',0,0,'Lâm'),
('letters','letters-م','Mîm',0,0,'Mîm'),
('letters','letters-ن','Nûn',0,0,'Nûn'),
('letters','letters-ه','Hâ (ه)',0,0,'Hâ (ه)'),
('letters','letters-و','Vâv',0,0,'Vâv'),
('letters','letters-ي','Yâ',0,0,'Yâ'),
('ordering','order-1-1','1. sıra',1,1,'Fâtiha'),
('ordering','order-1-2','2. sıra',1,2,'Fâtiha'),
('ordering','order-1-3','3. sıra',1,3,'Fâtiha'),
('ordering','order-1-4','4. sıra',1,4,'Fâtiha'),
('ordering','order-1-5','5. sıra',1,5,'Fâtiha'),
('ordering','order-1-6','6. sıra',1,6,'Fâtiha'),
('ordering','order-1-7','7. sıra',1,7,'Fâtiha'),
('ordering','order-112-1','1. sıra',112,1,'İhlâs'),
('ordering','order-112-2','2. sıra',112,2,'İhlâs'),
('ordering','order-112-3','3. sıra',112,3,'İhlâs'),
('ordering','order-112-4','4. sıra',112,4,'İhlâs'),
('ordering','order-113-1','1. sıra',113,1,'Felâk'),
('ordering','order-113-2','2. sıra',113,2,'Felâk'),
('ordering','order-113-3','3. sıra',113,3,'Felâk'),
('ordering','order-113-4','4. sıra',113,4,'Felâk'),
('ordering','order-113-5','5. sıra',113,5,'Felâk'),
('ordering','order-114-1','1. sıra',114,1,'Nâs'),
('ordering','order-114-2','2. sıra',114,2,'Nâs'),
('ordering','order-114-3','3. sıra',114,3,'Nâs'),
('ordering','order-114-4','4. sıra',114,4,'Nâs'),
('ordering','order-114-5','5. sıra',114,5,'Nâs'),
('ordering','order-114-6','6. sıra',114,6,'Nâs'),
('ordering','order-108-1','1. sıra',108,1,'Kevser'),
('ordering','order-108-2','2. sıra',108,2,'Kevser'),
('ordering','order-108-3','3. sıra',108,3,'Kevser'),
('ordering','order-103-1','1. sıra',103,1,'Asr'),
('ordering','order-103-2','2. sıra',103,2,'Asr'),
('ordering','order-103-3','3. sıra',103,3,'Asr'),
('ordering','order-109-1','1. sıra',109,1,'Kâfirûn'),
('ordering','order-109-2','2. sıra',109,2,'Kâfirûn'),
('ordering','order-109-3','3. sıra',109,3,'Kâfirûn'),
('ordering','order-109-4','4. sıra',109,4,'Kâfirûn'),
('ordering','order-109-5','5. sıra',109,5,'Kâfirûn'),
('ordering','order-109-6','6. sıra',109,6,'Kâfirûn')
ON CONFLICT(practice_type,question_id) DO UPDATE SET answer=EXCLUDED.answer,surah_id=EXCLUDED.surah_id,ayah=EXCLUDED.ayah,topic=EXCLUDED.topic;
COMMIT;
